### ISSUE TITLE
Occasional game freeze upon restarting on gem hunt

### ISSUE THREAD

**Issue by dflat2** [RandomityGuy/MBHaxe#43]
How to reproduce:

- Play [MBHaxe Ultra](https://marbleblastultra.randomityguy.me/).
- Start a gem hunt game on Sprawl (the freeze also occurred on Zenith and a few other maps iirc).
- Until the bug is triggered, do `Esc > Restart`.
- Game will eventually freeze, takes usually less than 10 restarts.

It seems to happen only in gem hunt.

**Comment by RandomityGuy** [comment]
Related to master server connectivity.

**Comment by dflat2** [comment]
I forgot to say that it happens in single player gem hunt, so I don't think it's related to server connectivity. Were you able to reproduce it?

**Comment by RandomityGuy** [comment]
Ok replicated the bug. Turns out one of multiplayer bugs relating to player spawns got carried over. Game keeps track of spawn points that are occupied so players don't spawn on each other. But that variable doesn't get reset on restart causing this bug. Basically game ran out of all the possible spawn points to spawn the marble at since it doesn't reset.

**Comment by RandomityGuy** [comment]
Fixed in 1.7.0

**Comment by dflat2** [comment]
If I'm not mistaken it's still happening on MBHaxe Ultra (v1.2.1). Restarting Sprawl 8 times freezes the game.

**Comment by RandomityGuy** [comment]
Ah man, replicated. Affects Singleplayer only.

**Comment by RandomityGuy** [comment]
Should be finally fixed in 1.2.2
